package vn.mran.bc3.constant;

import vn.mran.bc3.R;

/**
 * Created by Mr An on 28/11/2017.
 */

public interface PrefValue {
    String SETTING_SOUND = "SETTING_SOUND";
    int DEFAULT_QUANTUM = 0;
    String DEFAULT_STATUS = "off";
    String DEFAULT_TEXT = "Chúc các bạn chơi vui vẻ !";
    int DEFAULT_ADDITIONAL_NUMBER = 0;
    long DEFAULT_RULE = 1;
    int DEFAULT_MUSIC_ID = R.raw.wc_2002;
    String DEFAULT_ASSIGN_ARRAYS = "0 1 2 3 4 5";

    String MUSIC_ID = "MUSIC_ID";

    String CURRENT_RULE_CHILD = "CURRENT_RULE_CHILD";

    String RULE_1_ADDITIONAL_NUMBER = "RULE_1_ADDITIONAL_NUMBER";
    String RULE_1_ASSIGN_ARRAYS = "RULE_1_ASSIGN_ARRAYS";
    String RULE_1_QUANTUM = "RULE_1_QUANTUM";
    String RULE_1_STATUS = "RULE_1_STATUS";

    String RULE_2_ADDITIONAL_NUMBER = "RULE_2_ADDITIONAL_NUMBER";
    String RULE_2_ASSIGN_ARRAYS = "RULE_2_ASSIGN_ARRAYS";
    String RULE_2_QUANTUM = "RULE_2_QUANTUM";
    String RULE_2_STATUS = "RULE_2_STATUS";

    String RULE_3_ADDITIONAL_NUMBER = "RULE_3_ADDITIONAL_NUMBER";
    String RULE_3_ASSIGN_ARRAYS = "RULE_3_ASSIGN_ARRAYS";
    String RULE_3_QUANTUM = "RULE_3_QUANTUM";
    String RULE_3_STATUS = "RULE_3_STATUS";

    String RULE_MAIN_QUANTUM = "RULE_MAIN_QUANTUM";
    String RULE_MAIN_STATUS = "RULE_MAIN_STATUS";

    String TEXT = "TEXT";
    String HIDE_NUMBER = "HIDE_NUMBER";
}
