package vn.mran.bc3.constant;

/**
 * Created by Mr An on 28/11/2017.
 */

public interface PrefValue {
    String SETTING_SOUND = "SETTING_SOUND";
    int DEFAULT_QUANTUM = 10000;
    String DEFAULT_STATUS = "on";
    String DEFAULT_TEXT = "Chúc các bạn chơi vui ve";
    int DEFAULT_ADDITIONAL_NUMBER = 0;
    int DEFAULT_RULE = 1;
    int DEFAULT_ASSIGN_NUM_1 = 0;
    int DEFAULT_ASSIGN_NUM_2 = 1;
    int DEFAULT_ASSIGN_NUM_3 = 2;
    int DEFAULT_ASSIGN_NUM_4 = 3;
    int DEFAULT_ASSIGN_NUM_5 = 4;
    int DEFAULT_ASSIGN_NUM_6 = 5;


    String RULE_CHILD_ADDITIONAL_NUMBER = "RULE_CHILD_ADDITIONAL_NUMBER";
    String RULE_CHILD_NUM_1 = "RULE_CHILD_NUM_1";
    String RULE_CHILD_NUM_2 = "RULE_CHILD_NUM_2";
    String RULE_CHILD_NUM_3 = "RULE_CHILD_NUM_3";
    String RULE_CHILD_NUM_4 = "RULE_CHILD_NUM_4";
    String RULE_CHILD_NUM_5 = "RULE_CHILD_NUM_5";
    String RULE_CHILD_NUM_6 = "RULE_CHILD_NUM_6";
    String RULE_CHILD_QUANTUM = "RULE_CHILD_QUANTUM";
    String RULE_CHILD_RULE = "RULE_CHILD_RULE";
    String RULE_CHILD_STATUS = "RULE_CHILD_STATUS";

    String RULE_CHILD_PLAY_ADDITIONAL_NUMBER = "RULE_CHILD_PLAY_ADDITIONAL_NUMBER";
    String RULE_CHILD_PLAY_NUM_1 = "RULE_CHILD_PLAY_NUM_1";
    String RULE_CHILD_PLAY_NUM_2 = "RULE_CHILD_PLAY_NUM_2";
    String RULE_CHILD_PLAY_NUM_3 = "RULE_CHILD_PLAY_NUM_3";
    String RULE_CHILD_PLAY_NUM_4 = "RULE_CHILD_PLAY_NUM_4";
    String RULE_CHILD_PLAY_NUM_5 = "RULE_CHILD_PLAY_NUM_5";
    String RULE_CHILD_PLAY_NUM_6 = "RULE_CHILD_PLAY_NUM_6";
    String RULE_CHILD_PLAY_QUANTUM = "RULE_CHILD_PLAY_QUANTUM";
    String RULE_CHILD_PLAY_RULE = "RULE_CHILD_PLAY_RULE";
    String RULE_CHILD_PLAY_STATUS = "RULE_CHILD_PLAY_STATUS";

    String RULE_MAIN_QUANTUM = "RULE_MAIN_QUANTUM";
    String RULE_MAIN_STATUS = "RULE_MAIN_STATUS";

    String RULE_MAIN_PLAY_QUANTUM = "RULE_MAIN_PLAY_QUANTUM";
    String RULE_MAIN_PLAY_STATUS = "RULE_MAIN_PLAY_STATUS";

    String RULE_OFFLINE_ADDITIONAL_NUMBER = "RULE_OFFLINE_ADDITIONAL_NUMBER";
    String RULE_OFFLINE_NUM_1 = "RULE_OFFLINE_NUM_1";
    String RULE_OFFLINE_NUM_2 = "RULE_OFFLINE_NUM_2";
    String RULE_OFFLINE_NUM_3 = "RULE_OFFLINE_NUM_3";
    String RULE_OFFLINE_NUM_4 = "RULE_OFFLINE_NUM_4";
    String RULE_OFFLINE_NUM_5 = "RULE_OFFLINE_NUM_5";
    String RULE_OFFLINE_NUM_6 = "RULE_OFFLINE_NUM_6";
    String RULE_OFFLINE_QUANTUM = "RULE_OFFLINE_QUANTUM";
    String RULE_OFFLINE_STATUS = "RULE_OFFLINE_STATUS";

    String RULE_OFFLINE_PLAY_ADDITIONAL_NUMBER = "RULE_OFFLINE_PLAY_ADDITIONAL_NUMBER";
    String RULE_OFFLINE_PLAY_NUM_1 = "RULE_OFFLINE_PLAY_NUM_1";
    String RULE_OFFLINE_PLAY_NUM_2 = "RULE_OFFLINE_PLAY_NUM_2";
    String RULE_OFFLINE_PLAY_NUM_3 = "RULE_OFFLINE_PLAY_NUM_3";
    String RULE_OFFLINE_PLAY_NUM_4 = "RULE_OFFLINE_PLAY_NUM_4";
    String RULE_OFFLINE_PLAY_NUM_5 = "RULE_OFFLINE_PLAY_NUM_5";
    String RULE_OFFLINE_PLAY_NUM_6 = "RULE_OFFLINE_PLAY_NUM_6";
    String RULE_OFFLINE_PLAY_QUANTUM = "RULE_OFFLINE_PLAY_QUANTUM";
    String RULE_OFFLINE_PLAY_STATUS = "RULE_OFFLINE_PLAY_STATUS";

    String TEXT = "TEXT";
    String TEXT_PLAY = "TEXT_PLAY";

    String MONEY = "MONEY";
    int DEFAULT_MONEY = 5000;
}
